// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBV_NUU8vi1rvNIto4kTtdX7wqfM5Ht5xY',
    appId: '1:887650920323:web:a75810469294fba5abf8b6',
    messagingSenderId: '887650920323',
    projectId: 'doctorappointment-91859',
    authDomain: 'doctorappointment-91859.firebaseapp.com',
    storageBucket: 'doctorappointment-91859.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMs8k9DAb8_tt894llOPs8SrugUSJNwZM',
    appId: '1:887650920323:android:046943442a497d17abf8b6',
    messagingSenderId: '887650920323',
    projectId: 'doctorappointment-91859',
    storageBucket: 'doctorappointment-91859.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCoJ4N03XPpPutMn5zivqAsC8bSR7kjWTA',
    appId: '1:887650920323:ios:410ce550962faee9abf8b6',
    messagingSenderId: '887650920323',
    projectId: 'doctorappointment-91859',
    storageBucket: 'doctorappointment-91859.firebasestorage.app',
    iosBundleId: 'com.example.doctorappointmentapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBV_NUU8vi1rvNIto4kTtdX7wqfM5Ht5xY',
    appId: '1:887650920323:web:89dbe92b57756a6dabf8b6',
    messagingSenderId: '887650920323',
    projectId: 'doctorappointment-91859',
    authDomain: 'doctorappointment-91859.firebaseapp.com',
    storageBucket: 'doctorappointment-91859.firebasestorage.app',
  );
}
